try to fix docker build (but failed)
docker build --rm -f "Dockerfile" -t willh/mocky:latest "."

:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
unresolved dependency: org.scala-lang#scala-library;2.10.6: not found
unresolved dependency: org.scala-lang#scala-compiler;2.10.6: not found
unresolved dependency: org.scala-sbt#launcher-interface;1.0.1: not found
unresolved dependency: com.jcraft#jsch;0.1.50: not found
unresolved dependency: org.scala-lang.modules#scala-pickling_2.10;0.10.1: not found
unresolved dependency: org.json4s#json4s-core_2.10;3.2.10: not found
unresolved dependency: org.spire-math#jawn-parser_2.10;0.6.0: not found
unresolved dependency: org.spire-math#json4s-support_2.10;0.6.0: not found
unresolved dependency: org.scala-lang#scala-reflect;2.10.6: not found
Error during sbt execution: Error retrieving required libraries
  (see /root/.sbt/boot/update.log for complete log)
Error: Could not retrieve sbt 0.13.16
The command '/bin/sh -c sbt -Dsbt.override.build.repos=true -Dsbt.repository.secure=false dist' returned a non-zero code: 1